config/routes.rb
Rails.application.routes.draw do
  resources :features do
    resources :comments, only: [:new, :create]
  end


  # get 'comments/new'
  # get 'comments/create'
  # get 'features/index'
  # get 'features/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :feature

  validates :body, presence: true
end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, :external_url, :place, :mag_type, :longitude, :latitude, presence: true
  validates :magnitude, numericality: { greater_than_or_equal_to: -1.0, less_than_or_equal_to: 10.0 }
  validates :latitude, numericality: { greater_than_or_equal_to: -90.0, less_than_or_equal_to: 90.0 }
  validates :longitude, numericality: { greater_than_or_equal_to: -180.0, less_than_or_equal_to: 180.0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #before_action :set_feature, only: %i[new, create]

  def new
    @feature = Feature.find(params[:feature_id])
    @comment = Comment.new
  end

  def create
    @feature = Feature.find(params[:feature_id])
    @comment = Comment.new(comment_params)
    @comment.feature = @feature

    if @comment.save
      redirect_to feature_path(@comment.feature_id, anchor: "feature")
    else
      render :new
    end
  end

  private

  def set_feature
    @feature = Feature.find(params[:feature_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def index
    SismicDataService.fetch_and_save_data
    current_page = (params[:page].to_i || 1).to_i
    per_page = (params[:per_page].to_i || 10).to_i

    #api_data =
    @features = Feature.all
  end

  def show
    @feature = Feature.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Add new comment</h1>
<%= simple_form_for([@feature, @comment]) do |f| %>
  <%= f.input :body %>
  <%= f.submit "Submit comment", class: "btn btn-primary" %>
<% end %>

app/views/features/_feature.html.erb
<div id="<%= dom_id feature%>">
  <p>
    <strong>Title:</strong>
    <%= feature.title %>
  </p>
  <p>
    <strong>Place:</strong>
    <%= feature.place %>
  </p>
  <p>
    <strong>Magnitude Type:</strong>
    <%= feature.mag_type %>
  </p>
  <p>
    <strong>Magnitude:</strong>
    <%= feature.magnitude %>
  </p>
  <p>
    <strong>Time:</strong>
    <%= feature.time %>
  </p>
  <p>
    <strong>Tsunami:</strong>
    <%= feature.tsunami %>
  </p>
  <p>
    <strong>External Id:</strong>
    <%= feature.external_id %>
  </p>
  <%# <p>
    <strong>Coordinates:</strong>
    <%= feature.longitude, feature.latitude 
  </p> %>
</div>

app/views/features/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Features</h1>

<div id="features" style="width: 18rem;">
  <% @features.each do |feature| %>
    <div class="card">
      <ul>
        <li><strong>Title: </strong> <%= feature.title %></li>
        <li><strong>Place: </strong> <%= feature.place %></li>
        <li><strong>Magnitude Type:</strong> <%= feature.mag_type %></li>
      </ul>
      <p>
        <%= link_to "Show this feature", feature %>
      </p>
    </div>
  <% end %>
</div>

app/views/features/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @feature %>

<p><strong>Comments:</strong></p>
<ul class="list-group">
  <% @feature.comments.each do |comment| %>
    <li class="list-group-item"><%= comment.body %></li>
  <% end %>
</ul>
<br>
<div>
  <%= link_to "Add new comment", new_feature_comment_path(@feature) %>
  <%= link_to "Back to features", features_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EarthquakeRecords</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>